id: P004308
initial_creation_type: ocr
source_metadata:
  id: bdr:W1022
  title: གསུང་འབུམ། ཡེ་ཤེས་རྒྱལ་མཚན།
  author: ''
  volumes:
    aa3e37c1d8b74a9a89fa3092a6b29a2a:
      image_group_id: I1215
      title: ''
      volume_number: 1
      total_pages: 806
    d72eb9a029f6419eb994407d51bf4655:
      image_group_id: I1216
      title: ''
      volume_number: 2
      total_pages: 756
    5cb1eb5516fb497ba3624dc02422a223:
      image_group_id: I1217
      title: ''
      volume_number: 3
      total_pages: 556
    836a1cd861414e14bc6460c834de5fdb:
      image_group_id: I1218
      title: ''
      volume_number: 4
      total_pages: 578
    450420c5c8964089aeb59bea5343f881:
      image_group_id: I1219
      title: ''
      volume_number: 5
      total_pages: 460
    fcba0ec2bb674b9bbf2f244ebbbb5001:
      image_group_id: I1220
      title: ''
      volume_number: 6
      total_pages: 522
    f3b88540b66546e2a199b1446e70f79f:
      image_group_id: I1221
      title: ''
      volume_number: 7
      total_pages: 575
    097fd4649356421d9e4cee56bf66a8cf:
      image_group_id: I1222
      title: ''
      volume_number: 8
      total_pages: 494
    790056ef3a9d4ce9ac8aa1e0412bafba:
      image_group_id: I1223
      title: ''
      volume_number: 9
      total_pages: 686
    f5a2b98fb002473c96a7be18ee98b234:
      image_group_id: I1224
      title: ''
      volume_number: 10
      total_pages: 470
    80c042384907432b9441d26b09028a8a:
      image_group_id: I1225
      title: ''
      volume_number: 11
      total_pages: 614
    7af691e59c69421480dfcddef940ab21:
      image_group_id: I1226
      title: ''
      volume_number: 12
      total_pages: 468
    00af4db918b24063ba8d1b00d61c5a33:
      image_group_id: I1227
      title: ''
      volume_number: 13
      total_pages: 576
    469ef1c329014161a9a98c69df4d40fe:
      image_group_id: I1228
      title: ''
      volume_number: 14
      total_pages: 462
    f69d3e8a96884bec96a7ddba4409cca3:
      image_group_id: I1229
      title: ''
      volume_number: 15
      total_pages: 476
    5b97a06656354998b85243c2b59179d4:
      image_group_id: I1230
      title: ''
      volume_number: 16
      total_pages: 570
    77f5b1f20cd642cc8e635b1caf77b05f:
      image_group_id: I1231
      title: ''
      volume_number: 17
      total_pages: 496
    6936196558f847f0a859def920d88bad:
      image_group_id: I1232
      title: ''
      volume_number: 18
      total_pages: 510
    407e0537473f424d821f65a64c95f6d0:
      image_group_id: I1233
      title: ''
      volume_number: 19
      total_pages: 500
    f7cabd9135584f30ae90dc6a935466ce:
      image_group_id: I1234
      title: ''
      volume_number: 20
      total_pages: 560
    5c2abd8d839d4b57a9544910cb093cbf:
      image_group_id: I1235
      title: ''
      volume_number: 21
      total_pages: 524
    d2c8169eaa8540e29f360f5800da85ea:
      image_group_id: I1236
      title: ''
      volume_number: 22
      total_pages: 532
    3abeeec100c44c7ba189aa971039f286:
      image_group_id: I1237
      title: ''
      volume_number: 23
      total_pages: 510
    3fe75cd1a57c46c195295ec5c0f9c632:
      image_group_id: I1238
      title: ''
      volume_number: 24
      total_pages: 550
    c05b680fb3e748e8b27b6278ee5f082a:
      image_group_id: I1239
      title: ''
      volume_number: 25
      total_pages: 858
