id: IF45FCF33
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T05:09:56+00:00'
last_modified: '2022-06-07T21:52:20.317947+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1022
  title: གསུང་འབུམ། ཡེ་ཤེས་རྒྱལ་མཚན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4C56:
      image_group_id: I1215
      title: ''
      total_pages: 806
      order: 1
      base_file: 4C56.txt
    4CA2:
      image_group_id: I1216
      title: ''
      total_pages: 756
      order: 2
      base_file: 4CA2.txt
    '9399':
      image_group_id: I1217
      title: ''
      total_pages: 556
      order: 3
      base_file: 9399.txt
    C8B7:
      image_group_id: I1218
      title: ''
      total_pages: 578
      order: 4
      base_file: C8B7.txt
    F2C3:
      image_group_id: I1219
      title: ''
      total_pages: 460
      order: 5
      base_file: F2C3.txt
    A940:
      image_group_id: I1220
      title: ''
      total_pages: 522
      order: 6
      base_file: A940.txt
    A69B:
      image_group_id: I1221
      title: ''
      total_pages: 575
      order: 7
      base_file: A69B.txt
    0B9B:
      image_group_id: I1222
      title: ''
      total_pages: 494
      order: 8
      base_file: 0B9B.txt
    F324:
      image_group_id: I1223
      title: ''
      total_pages: 686
      order: 9
      base_file: F324.txt
    BBCC:
      image_group_id: I1224
      title: ''
      total_pages: 470
      order: 10
      base_file: BBCC.txt
    1C96:
      image_group_id: I1225
      title: ''
      total_pages: 614
      order: 11
      base_file: 1C96.txt
    1F76:
      image_group_id: I1226
      title: ''
      total_pages: 468
      order: 12
      base_file: 1F76.txt
    4C87:
      image_group_id: I1227
      title: ''
      total_pages: 576
      order: 13
      base_file: 4C87.txt
    449D:
      image_group_id: I1228
      title: ''
      total_pages: 462
      order: 14
      base_file: 449D.txt
    A3BA:
      image_group_id: I1229
      title: ''
      total_pages: 476
      order: 15
      base_file: A3BA.txt
    8A60:
      image_group_id: I1230
      title: ''
      total_pages: 570
      order: 16
      base_file: 8A60.txt
    AE4E:
      image_group_id: I1231
      title: ''
      total_pages: 496
      order: 17
      base_file: AE4E.txt
    0394:
      image_group_id: I1232
      title: ''
      total_pages: 510
      order: 18
      base_file: 0394.txt
    64BB:
      image_group_id: I1233
      title: ''
      total_pages: 500
      order: 19
      base_file: 64BB.txt
    B94F:
      image_group_id: I1234
      title: ''
      total_pages: 560
      order: 20
      base_file: B94F.txt
    FFCE:
      image_group_id: I1235
      title: ''
      total_pages: 524
      order: 21
      base_file: FFCE.txt
    9FE0:
      image_group_id: I1236
      title: ''
      total_pages: 532
      order: 22
      base_file: 9FE0.txt
    F014:
      image_group_id: I1237
      title: ''
      total_pages: 510
      order: 23
      base_file: F014.txt
    C41A:
      image_group_id: I1238
      title: ''
      total_pages: 550
      order: 24
      base_file: C41A.txt
    6B3C:
      image_group_id: I1239
      title: ''
      total_pages: 858
      order: 25
      base_file: 6B3C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
